package in.iitd.mldev.ui;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.MissingResourceException;
import java.util.ResourceBundle;

import org.eclipse.jface.preference.IPreferenceStore;
import org.eclipse.jface.preference.PreferenceConverter;
import org.eclipse.swt.graphics.RGB;
import org.eclipse.ui.editors.text.templates.ContributionContextTypeRegistry;
import org.eclipse.ui.editors.text.templates.ContributionTemplateStore;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.osgi.framework.BundleContext;

/** The main plugin class. Generated by Eclipse and not modified much.
 * Contains "global" string constants used as identifiers by many classes. */
/* TODO: write more TODOs */
public class SmlUiPlugin extends AbstractUIPlugin {
	//The shared instance.
	private static SmlUiPlugin plugin;
	
	/** Boolean attribute for whether bracket matching is enabled.
	 * We set it to true in initializeDefaultPluginPreferences,
	 * and never change it, so bracket matching is always on. */
	public static final String SML_BRACKET_MATCHING_ENABLED = "in.iitd.mldev.smlBracketMatchingEnabled";
	/** Color attribute for the color of the bracket matching box. */
	public static final String SML_BRACKET_MATCHING_COLOR = "in.iitd.mldev.smlBracketMatchingColor";

	/** Color attribute for the color for keywords in syntax highlighting. */
	public static final String SML_KEYWORD_COLOR = "in.iitd.mldev.smlKeywordColor";
	/** Color attribute for the color for strings in syntax highlighting. */
	public static final String SML_STRING_COLOR = "in.iitd.mldev.smlStringColor";
	/** Color attribute for the color for comments in syntax highlighting. */
	public static final String SML_COMMENT_COLOR = "in.iitd.mldev.smlCommentColor";
	public static final String SML_INT_COLOR = "in.iitd.mldev.smlIntColor";
	public static final String SML_REAL_COLOR = "in.iitd.mldev.smlRealColor";
	/** Integer attribute for the tab width. */
	public static final String SML_TAB_WIDTH = "in.iitd.mldev.smlTabWidth";
	/** Boolean attribute for whether to mark syntax errors in the editor. */
	public static final String SML_MARK_ERRORS = "in.iitd.mldev.smlMarkErrors";

	public static final String SML_RAINBOW_PAREN = "in.iitd.mldev.rainbowParen";
	public static final int SML_RAINBOW_PAREN_COUNT = 8;
	public static final RGB[] SML_RAINBOW_PAREN_DEFAULTS = new RGB[]{
		new RGB(212, 23, 142),
		new RGB(130, 3, 3),
		new RGB(40,161,50),
		new RGB(227,174,14),
		new RGB(100,127,209),
		new RGB(100, 204, 209),
		new RGB(237,230,14),
		new RGB(219,77,207),
	};

	public static final String TEMPLATE_KEY = "in.iitd.mldev.templatestore";
	//Resource bundle.
	private ResourceBundle resourceBundle;
	private ContributionContextTypeRegistry registry;
	private ContributionTemplateStore store;

	/**
	 * The constructor.
	 */
	public SmlUiPlugin () {
		super();
		plugin = this;
		try {
			resourceBundle = ResourceBundle.getBundle("in.iitd.mldev.ui.SmlUiPluginResources");
		} catch (MissingResourceException x) {
			resourceBundle = null;
		}
	}

	/**
	 * This method is called upon plug-in activation
	 */
	public void start (BundleContext context) throws Exception {
		super.start(context);
	}

	/**
	 * This method is called when the plug-in is stopped
	 */
	public void stop (BundleContext context) throws Exception {
		super.stop(context);
	}

	/**
	 * Returns the shared instance.
	 */
	public static SmlUiPlugin getDefault () {
		return plugin;
	}

	/** Initializes default values for this plug-in's preferences. */
	/* TODO: This is deprecated. See the deprecated comment in
	 * Plugin.initializeDefaultPluginPreferences. */
	@Override
	protected void initializeDefaultPluginPreferences () {
		IPreferenceStore store = getPreferenceStore();
		store.setDefault(SML_BRACKET_MATCHING_ENABLED, true);
		PreferenceConverter.setDefault(store, SML_BRACKET_MATCHING_COLOR, new RGB(192, 192, 192));
		PreferenceConverter.setDefault(store, SML_KEYWORD_COLOR, new RGB(128,0,128));
		PreferenceConverter.setDefault(store, SML_STRING_COLOR, new RGB(0,0,255));
		PreferenceConverter.setDefault(store, SML_COMMENT_COLOR, new RGB(0,128,0));
		PreferenceConverter.setDefault(store, SML_INT_COLOR, new RGB(128,128,0));
		PreferenceConverter.setDefault(store, SML_REAL_COLOR, new RGB(128,128,50));
		setupRainbowParenDefaults(store);
		store.setDefault(SML_TAB_WIDTH, 2);
		store.setDefault(SML_MARK_ERRORS, true);
	}

	private void setupRainbowParenDefaults(IPreferenceStore store) {
		List<String> keys = getRainbowParenStrings();
		for (int i = 0; i < keys.size(); i++) {
			PreferenceConverter.setDefault(store, keys.get(i), SML_RAINBOW_PAREN_DEFAULTS[i]);
		}
	}

	public static final List<String> getRainbowParenStrings() {
		List<String> rtn = new ArrayList<String>();
		for (int i = 0; i < SML_RAINBOW_PAREN_COUNT; i++) {
			rtn.add(SML_RAINBOW_PAREN + i);
		}
		return rtn;
	}

	/**
	 * Returns the string from the plugin's resource bundle,
	 * or 'key' if not found.
	 */
	public static String getResourceString (String key) {
		ResourceBundle bundle = SmlUiPlugin.getDefault().getResourceBundle();
		try {
			return (bundle != null) ? bundle.getString(key) : key;
		} catch (MissingResourceException e) {
			return key;
		}
	}

	/**
	 * Returns the plugin's resource bundle,
	 */
	public ResourceBundle getResourceBundle () {
		return resourceBundle;
	}
	
	public ContributionContextTypeRegistry getRegistry() {
		if(registry == null) {
			registry = new ContributionContextTypeRegistry();
			registry.addContextType("in.iitd.mldev.ui.SMLContextType");
		}
		return registry;
	}
	
	public ContributionTemplateStore getTemplateStore() {
		if(store == null) {
			store = new ContributionTemplateStore(getRegistry(), getPreferenceStore(), 
					SmlUiPlugin.TEMPLATE_KEY);
			try {
				store.load();
			} catch (IOException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
		return store;
	}

}